### ISSUE TITLE
ImportError: cannot import name 'MutableMapping' from 'collections

### ISSUE THREAD

**Issue by samihaq** [Faouzizi/Create_LoginPage#3]
G'day Faozizi,

I compile the requirements in windows 10 machine and getting below error.
C:\Create_LoginPage>python main.py
Traceback (most recent call last):
  File "C:\Users\samiu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\samiu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\samiu\AppData\Local\Programs\Python\Python310\Scripts\flask.exe\__main__.py", line 4, in <module>
  File "C:\Users\samiu\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "C:\Users\samiu\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 36, in <module>
    from .sessions import SecureCookieSessionInterface
  File "C:\Users\samiu\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\sessions.py", line 14, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (C:\Users\samiu\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)
Please advise

**Comment by samihaq** [comment]
issue is resolved on 3.9.0 Python.

**Comment by samihaq** [comment]
> G'day Faozizi,
> 
> I compile the requirements in windows 10 machine and getting below error. C:\Create_LoginPage>python main.py Traceback (most recent call last): File "C:\Users\samiu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Users\samiu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "C:\Users\samiu\AppData\Local\Programs\Python\Python310\Scripts\flask.exe__main__.py", line 4, in File "C:\Users\samiu\AppData\Local\Programs\Python\Python310\lib\site-packages\flask__init__.py", line 21, in from .app import Flask, Request, Response File "C:\Users\samiu\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 36, in from .sessions import SecureCookieSessionInterface File "C:\Users\samiu\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\sessions.py", line 14, in from collections import MutableMapping ImportError: cannot import name 'MutableMapping' from 'collections' (C:\Users\samiu\AppData\Local\Programs\Python\Python310\lib\collections__init_.py) Please advise_

I found Python 3.9.0 resolved the error message

**Comment by Faouzizi** [comment]
Thank you Samihaq
